[/Script/UnrealEd.CookerSettings]
bCookOnTheFlyForLaunchOnDevice=False

[/Script/AdvancedPreviewScene.LocalProfiles]
; VR-focused editor defaults

[/Script/UnrealEd.EditorPerformanceSettings]
bShowFrameRateAndMemory=False
